### ISSUE TITLE
Weather Retrieval Microservice

### ISSUE THREAD

**Issue by AnshulV98** [airavata-courses/VignyaanDwaarNirman#7]
Implement current weather microservice

**Comment by devanshjain14** [comment]
Please clarify, does this mean the current data retrieval or historical data retrieval?

**Comment by ViralPrajapati** [comment]
Its current data retrieval and I have successfully completed implemented it.

**Comment by devanshjain14** [comment]
I doubt if we should do this as a microservice or not? According to @smarru, we should only develop microservice where some computations are being done. 

Since this is just an add-on service, I think, implementing this on the UI part will not be much of a problem. 

Nevertheless, I invite your and @AnshulV98 suggestions on this point.

**Comment by devanshjain14** [comment]
I doubt if we should do this as a microservice or not? According to @smarru, we should only develop microservice where some computations are being done. 

Since this is just an add-on service, I think, implementing this on the UI part will not be much of a problem. 

Nevertheless, I invite your and @AnshulV98 suggestions on this point.

**Comment by ViralPrajapati** [comment]
I have started integrating the weather forecasting microservices and it seems that even though I can download the required radar file from nexrad data and plot required maps locally, I am not able to replicate this results in the microservices. In fact I am not even able to setup connection with the aws nexrad dataset via microservices. 
![issue](https://user-images.githubusercontent.com/30920198/73979127-9b6fad80-48fb-11ea-8ec4-34df6079007c.PNG)
